version: '3.1'
services:
  qbe-postgres:
    image: postgres:12
    container_name: ${QBE_PROJECT_NAME}-postgres
    restart: unless-stopped
    volumes:
      - "./database/local:/var/lib/postgresql/data"
      - "./migration/migration.sh:/docker-entrypoint-initdb.d/init-database.sh"
    environment:
      - POSTGRES_USER=${QBE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${QBE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${QBE_PROJECT_ENV}_${QBE_POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      backend_network:
        ipv4_address: 172.29.1.2
  qbe-php-fpm:
    build:
      context: ./api-src
      dockerfile: ../webserver/php-fpm/Dockerfile
    container_name: ${QBE_PROJECT_NAME}-php-fpm
    restart: unless-stopped
    tty: true
    working_dir: /var/www/
    volumes:
      - ./api-src:/var/www/
    environment:
      - POSTGRES_HOST=qbe-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${QBE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${QBE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${QBE_PROJECT_ENV}_${QBE_POSTGRES_DB}
    depends_on:
      - qbe-postgres
    networks:
      backend_network:
        ipv4_address: 172.29.1.3
  qbe-webserver:
    image: nginx:stable
    container_name: ${QBE_PROJECT_NAME}-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
    working_dir: /var/www/
    volumes:
      - ./api-src:/var/www
      - ./webserver/nginx/backend.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - qbe-php-fpm
    links:
      - qbe-php-fpm
    networks:
      backend_network:
        ipv4_address: 172.29.1.4
  qbe-migration:
    image: postgres:latest
    container_name: ${QBE_PROJECT_NAME}-migration
    user: root
    command: ["./docker-entrypoint-initdb.d/init-database.sh"]
    links:
      - qbe-postgres
    depends_on:
      - qbe-postgres
      - qbe-webserver
      - qbe-php-fpm
networks:
  backend_network:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
